"""
/*
This has been generated by the overpass-turbo wizard.
The original search was:
“waterway=canal in Birmingham”
*/
[out:json][timeout:200];
// fetch area “Staffordshire” to search in
{{geocodeArea:United Kingdom}}->.searchArea;
// gather results
(
  nwr["waterway"="canal"](area.searchArea);
  nwr["waterway"="river"]["boat"="yes"](area.searchArea);
//nwr["leisure"="marina"](area.searchArea);
// nwr["water"="basin"](area.searchArea);
 );
// print results
out geom;
"""

import json
import pprint
# import overpass
# api = overpass.API(timeout=240)

# response = api.get("""
# area[name="United Kingdom"];
# (
# nwr["waterway"="canal"](area);
# nwr["waterway"="river"]["boat"="yes"](area);
# );
# 				   """)

# print(response)


import requests, osm2geojson

query = """
[out:json][timeout:200];
area(id:3600062149)->.searchArea;
(
nwr["waterway"="canal"](area.searchArea);
nwr["waterway"="river"]["boat"="yes"](area.searchArea);
nwr["tunnel"="canal"]["towpath"="yes"](area.searchArea);
nwr["leisure"="marina"](area.searchArea);
nwr["water"="basin"](area.searchArea);
nwr["water"="reservoir"](area.searchArea);
);
out geom;
"""

# query = """
# [out:json][timeout:200];
# area[name="United Kingdom"];
# (
# nwr["waterway"="canal"](area);
# nwr["waterway"="river"]["boat"="yes"](area);
# );
# out geom;
# """

resp = requests.post("https://overpass-api.de/api/interpreter", data=query, headers={"Content-Type": "application/x-www-form-urlencoded; charset=UTF-8"})

resp.raise_for_status()
# print(resp)
# print(resp.text)
# pprint.pprint(resp.json())

data = osm2geojson.json2geojson(resp.json())

with open("data.geojson", "w", encoding="UTF-8") as fp:
	json.dump(data, fp, indent=2)